-- MySQL Script generated by MySQL Workbench
-- sex 10 jul 2020 12:03:02 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bp_renegociacao
-- -----------------------------------------------------
-- Concebido inicialmente como sistema de registro de negociações da equipe 
-- de renegociação vacation.
DROP SCHEMA IF EXISTS `bp_renegociacao` ;

-- -----------------------------------------------------
-- Schema bp_renegociacao
--
-- Concebido inicialmente como sistema de registro de negociações da equipe 
-- de renegociação vacation.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bp_renegociacao` ;
USE `bp_renegociacao` ;

-- -----------------------------------------------------
-- Table `bp_renegociacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT(1) NULL,
  `data_criacao` DATETIME NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `ts_usuario_id` INT NULL,
  `matricula` VARCHAR(22) NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO usuario (ativo, data_criacao, nome, email, password) values (1, now(), 'admin', 'admin@beachpark.com.br', md5('123456'));
-- -----------------------------------------------------
-- Table `bp_renegociacao`.`origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`tipo_solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`tipo_solicitacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`situacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`ocorrencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idocorrencia` BIGINT(20) NULL,
  `status` CHAR(1) NULL,
  `idmotivots` INT NULL,
  `dtocorrencia` DATETIME NULL,
  `idcliente` BIGINT(20) NULL,
  `numeroprojeto` INT NULL,
  `numerocontrato` BIGINT(20) NULL,
  `idusuarioresp` INT NULL COMMENT 'CM.USUARIOSISTEMA',
  `atendida` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`negociacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`negociacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `origem_id` INT NULL,
  `tipo_solicitacao_id` INT NULL,
  `situacao_id` INT NULL,
  `data_criacao` DATETIME(6) NULL,
  `data_finalizacao` DATETIME(6) NULL,
  `observacao` LONGTEXT NULL,
  `finalizada` TINYINT(1) NULL,
  `motivo_cancelamento_ocorrencia_id` INT NULL,
  `ocorrencia_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_caixa_renegociacao_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_caixa_renegociacao_origem1_idx` (`origem_id` ASC),
  INDEX `fk_caixa_renegociacao_tipo_solicitacao1_idx` (`tipo_solicitacao_id` ASC),
  INDEX `fk_caixa_renegociacao_situacao1_idx` (`situacao_id` ASC),
  INDEX `fk_negociacao_ocorrencia1_idx` (`ocorrencia_id` ASC),
  CONSTRAINT `fk_caixa_renegociacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bp_renegociacao`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_origem1`
    FOREIGN KEY (`origem_id`)
    REFERENCES `bp_renegociacao`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_tipo_solicitacao1`
    FOREIGN KEY (`tipo_solicitacao_id`)
    REFERENCES `bp_renegociacao`.`tipo_solicitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_situacao1`
    FOREIGN KEY (`situacao_id`)
    REFERENCES `bp_renegociacao`.`situacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_negociacao_ocorrencia1`
    FOREIGN KEY (`ocorrencia_id`)
    REFERENCES `bp_renegociacao`.`ocorrencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'equi. caixa_renegociacao';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;