-- MySQL Script generated by MySQL Workbench
-- qua 05 ago 2020 16:17:18 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bp_renegociacao
-- -----------------------------------------------------
-- Concebido inicialmente como sistema de registro de negociações da equipe 
-- de renegociação vacation.
DROP SCHEMA IF EXISTS `bp_renegociacao` ;

-- -----------------------------------------------------
-- Schema bp_renegociacao
--
-- Concebido inicialmente como sistema de registro de negociações da equipe 
-- de renegociação vacation.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bp_renegociacao` ;
USE `bp_renegociacao` ;

-- -----------------------------------------------------
-- Table `bp_renegociacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT(1) NULL DEFAULT 1,
  `primeiro_nome` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `ts_usuario_id` INT NOT NULL,
  `matricula` VARCHAR(22) NULL,
  `created_at` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(2) NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`tipo_solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`tipo_solicitacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`situacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`ocorrencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idvendats` BIGINT(20) NULL,
  `idvendaxcontrato` BIGINT(20) NULL,
  `numero_ocorrencia` BIGINT(20) NULL,
  `status` CHAR(1) NULL,
  `ts_motivo_id` INT NULL,
  `dtocorrencia` DATETIME NULL,
  `ts_cliente_id` BIGINT(20) NULL,
  `nome_cliente` VARCHAR(100) NULL,
  `numero_projeto` INT NULL,
  `numero_contrato` BIGINT(20) NULL,
  `nome_projeto` VARCHAR(100) NULL,
  `data_venda` DATE NULL,
  `valor_venda_view` DECIMAL(10,2) NULL,
  `ts_usuario_resp_id` INT NULL COMMENT 'CM.USUARIOSISTEMA',
  `ts_usuario_resp_nome` VARCHAR(45) NULL,
  `atendida` TINYINT(1) NULL DEFAULT 0 COMMENT 'for internal application control',
  `created_at` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(2) NULL ON UPDATE CURRENT_TIMESTAMP,
  `valor_venda_res_fin` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`negociacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`negociacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `origem_id` INT NULL,
  `tipo_solicitacao_id` INT NULL,
  `situacao_id` INT NULL,
  `ocorrencia_id` INT NULL,
  `data_finalizacao` DATETIME(2) NULL,
  `observacao` LONGTEXT NULL,
  `finalizada` TINYINT(1) NULL,
  `motivo_cancelamento_ocorrencia_id` INT NULL,
  `created_at` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(2) NULL ON UPDATE CURRENT_TIMESTAMP,
  `multa` DECIMAL(10,2) NULL,
  `reembolso` DECIMAL(10,2) NULL,
  `numero_pc` VARCHAR(10) NULL,
  `taxas_extras` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_caixa_renegociacao_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_caixa_renegociacao_origem1_idx` (`origem_id` ASC),
  INDEX `fk_caixa_renegociacao_tipo_solicitacao1_idx` (`tipo_solicitacao_id` ASC),
  INDEX `fk_caixa_renegociacao_situacao1_idx` (`situacao_id` ASC),
  INDEX `fk_negociacao_ocorrencia1_idx` (`ocorrencia_id` ASC),
  CONSTRAINT `fk_caixa_renegociacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bp_renegociacao`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_origem1`
    FOREIGN KEY (`origem_id`)
    REFERENCES `bp_renegociacao`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_tipo_solicitacao1`
    FOREIGN KEY (`tipo_solicitacao_id`)
    REFERENCES `bp_renegociacao`.`tipo_solicitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caixa_renegociacao_situacao1`
    FOREIGN KEY (`situacao_id`)
    REFERENCES `bp_renegociacao`.`situacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_negociacao_ocorrencia1`
    FOREIGN KEY (`ocorrencia_id`)
    REFERENCES `bp_renegociacao`.`ocorrencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'equi. caixa_renegociacao';


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`motivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmotivots` INT NULL,
  `codreduzido` VARCHAR(3) NULL,
  `descricao` VARCHAR(100) NULL,
  `aplicacao` CHAR(1) NULL,
  `flgativo` CHAR(1) NULL,
  `trgdtinclusao` DATETIME NULL,
  `created_at` TIMESTAMP(2) NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(2) NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`retencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`retencao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `negociacao_id` INT NOT NULL,
  `contrato_id` INT NULL,
  `data` DATETIME NULL,
  `valor_antigo` DECIMAL(10,2) NULL,
  `valor_novo` DECIMAL(10,2) NULL,
  `valor_primeira_parcela` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_retencao_negociacao1_idx` (`negociacao_id` ASC),
  CONSTRAINT `fk_retencao_negociacao1`
    FOREIGN KEY (`negociacao_id`)
    REFERENCES `bp_renegociacao`.`negociacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bp_renegociacao`.`reversao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bp_renegociacao`.`reversao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `negociacao_id` INT NOT NULL,
  `data` DATETIME NULL,
  `valor_primeira_parcela` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reversao_negociacao1_idx` (`negociacao_id` ASC),
  CONSTRAINT `fk_reversao_negociacao1`
    FOREIGN KEY (`negociacao_id`)
    REFERENCES `bp_renegociacao`.`negociacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;