-- Query: cm_ocorrencias_ts_renegociacao
-- Descri��o: Busca todas as ocorr�ncias direcionadas para o departamento ADM TS - RENEGOCIA��O e relaciona o contrato a qual
---- a ocorr�ncia foi direcionada e seus respectivos valores
-- �ltimo ajuste: 01/05/2020
-- Isolada somente a consulta que retorna as ocorr�ncias do cliente adaptando para trazer um consolidado geral
-- Ano Ocorr�ncia = 2018 ate hoje (28-04-2020): 10.703  Linhas / iddepartamento = 3 (ADM TS - RENEGOCIA��O) / DESENVOLVIMENTO
-- Ano Ocorr�ncia = 2018 ate hoje (28-04-2020): 15.068  Linhas / iddepartamento = 3 (ADM TS - RENEGOCIA��O) / PRODU��O
SELECT
        O.IDOCORRENCIA                          AS NUM_OCORRENCIA,
        O.IDVENDAXCONTRATO                      AS OC_IDVENDAXCONTRATO,
        VC.IDVENDATS                            AS VXC_IDVENDATS,
        DECODE(O.STATUS, 'F', 'Finalizado',
                         'P', 'Pendente',
                         'C', 'Cancelado')      AS STATUS_OCORRENCIA,
        O.IDMOTIVOTS                            AS ID_MOTIVO,
        M.DESCRICAO                             AS MOTIVO,
        TO_CHAR(O.DTOCORRENCIA, 'DD/MM/YYYY')   AS DATA_OCORRENCIA,
        D.IDDEPARTAMENTO,
        D.DESCRICAO                             AS DEPARTAMENTO, 
        MF.IDMOTIVOTS                           AS ID_MOTIVO_FINALIZACAO,
        MF.DESCRICAO                            AS MOTIVO_FINALIZACAO,
        U.IDUSUARIO                             AS ID_USUARIO_CADASTRO,
        U.NOMEUSUARIO                           AS USUARIO_CADASTRO,
        P.IDPESSOA                              AS IDCLIENTE,
        P.NOME                                  AS NOMECLIENTE,
        PR.NUMEROPROJETO                        AS PROJETO,
        VC.NUMEROCONTRATO                       AS CONTRATO,
        TO_CHAR(TO_NUMBER(PR.NUMEROPROJETO)) || TO_CHAR(TO_NUMBER(VC.NUMEROCONTRATO)) AS PROJ_CONTRATO,
        VC.FLGREVERTIDO,
        VC.FLGCANCELADO,
        TO_NUMBER(
        CASE 
            WHEN CONTRATOSREVERTIDOS.IDREVCONTRATOTS IS NOT NULL THEN                  
                CASE
                    WHEN CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO < CONTRATOSREVERTIDOS.VALORFINAL THEN
                         CASE WHEN CONTRATOSREVERTIDOS.VALORFINAL < VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO THEN -- TESTE
                         VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO
                         ELSE
                         CONTRATOSREVERTIDOS.VALORFINAL
                         END
                    ELSE
                        CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO
                 END
            WHEN CONTRATOSCANCELADOS.IDCANCCONTRATOTS IS NOT NULL THEN
                 CASE 
                    WHEN CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO < VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO THEN -- teste
                        VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO
                    WHEN CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO < CONTRATOSCANCELADOS.VALORFINAL THEN 
                         CONTRATOSCANCELADOS.VALORFINAL
                    ELSE
                        CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO
                 END       
            ELSE 
                -- VALORVENDANORMAL.VALORCONTRATONORMAL                 
                VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO + NVL(VALORJUROSVENDANORMAL.VALORJUROSVENDANORMAL, 0) -- TESTE
        END)                                    AS VALORVENDA,
        UR.IDUSUARIO                            AS ID_US_RESP,
        UR.NOMEUSUARIO                          AS USUARIO_RESP,
        --DEBUG        
        VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO,
        VALORVENDANORMAL.VALORCONTRATONORMAL,
        VALORJUROSVENDANORMAL.VALORJUROSVENDANORMAL,
        CONTRATOSREVERTIDOS.IDREVCONTRATOTS,
        CONTRATOSREVERTIDOS.DATAREVERSAO,
        CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO,
        CONTRATOSREVERTIDOS.VALORFINAL AS VALORFINALREV,
        CONTRATOSCANCELADOS.IDCANCCONTRATOTS,
        CONTRATOSCANCELADOS.DATACANCELAMENTO,
        CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO,
        CONTRATOSCANCELADOS.VALORFINAL
FROM
        OCORRENCIATS      O,
        DEPARTAMENTOTS    D,
        MOTIVOTS          M,
        PESSOA            P,
        USUARIOSISTEMA    U,
        USUARIOSISTEMA   UR,
        VENDAXCONTRATOTS VC,
        CONTRATOTS        C,
        PROJETOTS        PR,
        MOTIVOTS         MF,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                VXC.IDVENDATS,
                RC.DATAREVERSAO,
                RC.IDREVCONTRATOTS,
                RC.IDMOTIVO,
                MT.DESCRICAO AS MOTIVOREVERSAO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATOREVERTIDO,
                VXC.VALORFINAL
           FROM 
                VENDAXCONTRATOTS VXC,
                REVCONTRATOTS RC,
                MOTIVOTS MT,
                LANCAMENTOTS L
          WHERE 
                VXC.IDVENDAXCONTRATO = RC.IDVENDAXCONTRNOVO
                AND RC.IDMOTIVO = MT.IDMOTIVOTS (+)
                AND VXC.IDVENDATS = L.IDVENDATS (+)
                AND L.IDREVCONTRATOTS IS NOT NULL
                AND L.IDLANCESTORNO IS NULL -- TESTE 
                AND L.VLRLANCAMENTO > 0
                AND L.IDTIPOLANCAMENTO IN (1, 7)
       GROUP BY 
                VXC.IDVENDAXCONTRATO,
                VXC.IDVENDATS,
                RC.DATAREVERSAO,
                RC.IDREVCONTRATOTS,
                RC.IDMOTIVO,
                MT.DESCRICAO,
                VXC.VALORFINAL) CONTRATOSREVERTIDOS,
        (SELECT
                VXC.IDVENDAXCONTRATO,                
                CC.IDCANCCONTRATOTS,
                CC.DATACANCELAMENTO,
                VXC.VALORFINAL,
                SUM(ABS(L.VLRLANCAMENTO)) AS VALORCONTRATOCANCELADO
           FROM
                     LANCAMENTOTS L,
                     VENDAXCONTRATOTS VXC,
                     CANCCONTRATOTS CC
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.IDCANCCONTRATOTS = CC.IDCANCCONTRATOTS
                AND CC.IDVENDAXCONTRATO = VXC.IDVENDAXCONTRATO
                AND L.IDTIPOLANCAMENTO IN (1,7)
                AND L.IDMOTIVOESTORNO IS NOT NULL
       GROUP BY 
                VXC.IDVENDAXCONTRATO, CC.IDCANCCONTRATOTS, CC.DATACANCELAMENTO, vxc.valorfinal) CONTRATOSCANCELADOS,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATONORMAL
           FROM
                LANCAMENTOTS L,
                VENDAXCONTRATOTS VXC
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.VLRLANCAMENTO > 0
                AND L.IDREVCONTRATOTS IS NULL
                AND L.IDCANCCONTRATOTS IS NULL
                AND L.IDTIPOLANCAMENTO IN (1, 7)
       GROUP BY VXC.IDVENDAXCONTRATO) VALORVENDANORMAL,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                SUM(L.VLRLANCAMENTO) AS VALORJUROSVENDANORMAL
           FROM
                LANCAMENTOTS L,
                VENDAXCONTRATOTS VXC,
                AJUSTEFINANCTS AJ
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.IDAJUSTEFINANCTS = AJ.IDAJUSTEFINANCTS (+)
                -- AND L.VLRLANCAMENTO > 0 TESTE
                AND L.IDREVCONTRATOTS IS NULL
                AND L.IDCANCCONTRATOTS IS NULL
                AND L.IDTIPOLANCAMENTO = 7
                AND AJ.IDMOTIVO <> 3
       GROUP BY VXC.IDVENDAXCONTRATO) VALORJUROSVENDANORMAL,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                VXC.TRGDTINCLUSAO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATOTRGDTINCLUSAO
            FROM
                VENDAXCONTRATOTS VXC,
                LANCAMENTOTS L    
            WHERE
                VXC.IDVENDATS = L.IDVENDATS 
                AND TRUNC(VXC.TRGDTINCLUSAO) = TRUNC(L.TRGDTINCLUSAO)
                AND L.VLRLANCAMENTO > 0
                AND L.IDTIPOLANCAMENTO IN (1, 7)
                GROUP BY VXC.IDVENDAXCONTRATO, VXC.TRGDTINCLUSAO) VALORVENDATRGDTINCLUSAO
WHERE
        O.IDDEPARTAMENTO = D.IDDEPARTAMENTO
        AND O.IDCLIENTE = P.IDPESSOA (+) -- LEFT JOIN
        AND O.IDMOTIVOTS = M.IDMOTIVOTS
        AND O.IDUSUARIO = U.IDUSUARIO
        AND O.IDVENDAXCONTRATO = VC.IDVENDAXCONTRATO (+) -- LEFT JOIN
        AND VC.IDCONTRATOTS = C.IDCONTRATOTS (+) -- LEFT JOIN
        AND VC.IDPROJETOTS = PR.IDPROJETOTS (+) -- LEFT JOIN
        AND O.USUARIORESP = UR.IDUSUARIO (+) -- LEFT JOIN
        AND O.IDMOTIVOFINALIZA  = MF.IDMOTIVOTS (+) -- LEFT JOIN
        AND O.IDVENDAXCONTRATO = CONTRATOSREVERTIDOS.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = CONTRATOSCANCELADOS.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORVENDANORMAL.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORJUROSVENDANORMAL.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORVENDATRGDTINCLUSAO.IDVENDAXCONTRATO (+)
        AND TO_DATE(TO_CHAR(O.DTOCORRENCIA,'dd/mm/yyyy'), 'dd/mm/yyyy') >= TO_DATE('15/06/2020', 'dd/mm/yyyy')
        AND D.IDDEPARTAMENTO IN (3, 83) -- ADM TS - RENEGOCIA��O
        -- AND P.IDPESSOA = 2427592 -- MARCELO AUGUSTO AMORIM - VC 
        -- AND P.IDPESSOA = 2472922 -- MORENO AUGUSTO DE ALMEIDA BARRETO - VC / RETEN��O MUDAN�A DE VALOR
        -- AND P.IDPESSOA = 2225781 -- GILDELAN FRANCISCO CORDEIRO DE SOUZA - VC  / UPGRADE
        -- AND P.IDPESSOA = 2291628 -- ALINE WALDECK RIBEIRO - VC / MANU / VARIOS LAN�AMENTO NA TABELA LANCAMENTOTS COM A MESMA DATA EM TRGDTINCLUSAO E  JUROS COM ERRO OPERACIONAL
        -- AND P.IDPESSOA = 2267752 -- MARCUS JOSE CORDEIRO SARNEY - VC / VALORES COM JUROS
        -- AND P.IDPESSOA = 937784  -- GLAUBER PESSOA BRANCO - VC / BIANCA /  VALORES COM JUROS
        -- AND P.IDPESSOA = 1191237 -- LARA LAVINIA TOMAZ BENTO - VC
        -- AND P.IDPESSOA = 2117904
        AND UR.IDUSUARIO = 640054
        ORDER BY O.DTOCORRENCIA ASC