SELECT
        O.IDOCORRENCIA                                   AS NUMERO_OCORRENCIA,
        O.IDVENDAXCONTRATO,
        VC.IDVENDATS,
        O.STATUS,
        O.IDMOTIVOTS                                     AS TS_MOTIVO_ID,
        M.DESCRICAO                                      AS MOTIVO,
        TO_CHAR(O.DTOCORRENCIA, 'YYYY-MM-DD HH24:MI:SS') AS DTOCORRENCIA,
        D.IDDEPARTAMENTO,
        D.DESCRICAO                                      AS DEPARTAMENTO,
        MF.IDMOTIVOTS                                    AS ID_MOTIVO_FINALIZACAO,
        MF.DESCRICAO                                     AS MOTIVO_FINALIZACAO,
        U.IDUSUARIO                                      AS ID_USUARIO_CADASTRO,
        U.NOMEUSUARIO                                    AS USUARIO_CADASTRO,
        P.IDPESSOA                                       AS TS_CLIENTE_ID,
        P.NOME                                           AS NOME_CLIENTE,
        PR.NUMEROPROJETO                                 AS NUMERO_PROJETO,
        VC.NUMEROCONTRATO                                AS NUMERO_CONTRATO,
        PR.NOMEPROJETO                                   AS NOME_PROJETO,
        VC.FLGREVERTIDO,
        VC.FLGCANCELADO,
        TO_NUMBER(
        CASE 
            WHEN CONTRATOSREVERTIDOS.IDREVCONTRATOTS IS NOT NULL THEN                  
                CASE
                    WHEN CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO < CONTRATOSREVERTIDOS.VALORFINAL THEN
                         CASE WHEN CONTRATOSREVERTIDOS.VALORFINAL < VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO THEN -- TESTE
                         VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO
                         ELSE
                         CONTRATOSREVERTIDOS.VALORFINAL
                         END
                    ELSE
                        CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO
                 END
            WHEN CONTRATOSCANCELADOS.IDCANCCONTRATOTS IS NOT NULL THEN
                 CASE 
                    WHEN CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO < VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO THEN -- teste
                        VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO
                    WHEN CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO < CONTRATOSCANCELADOS.VALORFINAL THEN 
                         CONTRATOSCANCELADOS.VALORFINAL
                    ELSE
                        CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO
                 END       
            ELSE 
                -- VALORVENDANORMAL.VALORCONTRATONORMAL                 
                VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO + NVL(VALORJUROSVENDANORMAL.VALORJUROSVENDANORMAL, 0) -- TESTE
        END)                                    AS VALOR_VENDA,
        UR.IDUSUARIO                            AS TS_USUARIO_RESP_ID, 
        UR.NOMEUSUARIO                          AS TS_USUARIO_RESP_NOME,
        --DEBUG        
        VALORVENDATRGDTINCLUSAO.VALORCONTRATOTRGDTINCLUSAO,
        VALORVENDANORMAL.VALORCONTRATONORMAL,
        VALORJUROSVENDANORMAL.VALORJUROSVENDANORMAL,
        CONTRATOSREVERTIDOS.IDREVCONTRATOTS,
        CONTRATOSREVERTIDOS.DATAREVERSAO,
        CONTRATOSREVERTIDOS.VALORCONTRATOREVERTIDO,
        CONTRATOSREVERTIDOS.VALORFINAL AS VALORFINALREV,
        CONTRATOSCANCELADOS.IDCANCCONTRATOTS,
        CONTRATOSCANCELADOS.DATACANCELAMENTO,
        CONTRATOSCANCELADOS.VALORCONTRATOCANCELADO,
        CONTRATOSCANCELADOS.VALORFINAL
FROM
        OCORRENCIATS      O,
        DEPARTAMENTOTS    D,
        MOTIVOTS          M,
        PESSOA            P,
        USUARIOSISTEMA    U,
        USUARIOSISTEMA   UR,
        VENDAXCONTRATOTS VC,
        CONTRATOTS        C,
        PROJETOTS        PR,
        MOTIVOTS         MF,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                VXC.IDVENDATS,
                RC.DATAREVERSAO,
                RC.IDREVCONTRATOTS,
                RC.IDMOTIVO,
                MT.DESCRICAO AS MOTIVOREVERSAO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATOREVERTIDO,
                VXC.VALORFINAL
           FROM 
                VENDAXCONTRATOTS VXC,
                REVCONTRATOTS RC,
                MOTIVOTS MT,
                LANCAMENTOTS L
          WHERE 
                VXC.IDVENDAXCONTRATO = RC.IDVENDAXCONTRNOVO
                AND RC.IDMOTIVO = MT.IDMOTIVOTS (+)
                AND VXC.IDVENDATS = L.IDVENDATS (+)
                AND L.IDREVCONTRATOTS IS NOT NULL
                AND L.IDLANCESTORNO IS NULL -- TESTE 
                AND L.VLRLANCAMENTO > 0
                AND L.IDTIPOLANCAMENTO IN (1, 7)
       GROUP BY 
                VXC.IDVENDAXCONTRATO,
                VXC.IDVENDATS,
                RC.DATAREVERSAO,
                RC.IDREVCONTRATOTS,
                RC.IDMOTIVO,
                MT.DESCRICAO,
                VXC.VALORFINAL) CONTRATOSREVERTIDOS,
        (SELECT
                VXC.IDVENDAXCONTRATO,                
                CC.IDCANCCONTRATOTS,
                CC.DATACANCELAMENTO,
                VXC.VALORFINAL,
                SUM(ABS(L.VLRLANCAMENTO)) AS VALORCONTRATOCANCELADO
           FROM
                     LANCAMENTOTS L,
                     VENDAXCONTRATOTS VXC,
                     CANCCONTRATOTS CC
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.IDCANCCONTRATOTS = CC.IDCANCCONTRATOTS
                AND CC.IDVENDAXCONTRATO = VXC.IDVENDAXCONTRATO
                AND L.IDTIPOLANCAMENTO IN (1,7)
                AND L.IDMOTIVOESTORNO IS NOT NULL
       GROUP BY 
                VXC.IDVENDAXCONTRATO, CC.IDCANCCONTRATOTS, CC.DATACANCELAMENTO, vxc.valorfinal) CONTRATOSCANCELADOS,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATONORMAL
           FROM
                LANCAMENTOTS L,
                VENDAXCONTRATOTS VXC
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.VLRLANCAMENTO > 0
                AND L.IDREVCONTRATOTS IS NULL
                AND L.IDCANCCONTRATOTS IS NULL
                AND L.IDTIPOLANCAMENTO IN (1, 7)
       GROUP BY VXC.IDVENDAXCONTRATO) VALORVENDANORMAL,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                SUM(L.VLRLANCAMENTO) AS VALORJUROSVENDANORMAL
           FROM
                LANCAMENTOTS L,
                VENDAXCONTRATOTS VXC,
                AJUSTEFINANCTS AJ
          WHERE
                L.IDVENDATS = VXC.IDVENDATS
                AND L.IDAJUSTEFINANCTS = AJ.IDAJUSTEFINANCTS (+)
                AND L.IDREVCONTRATOTS IS NULL
                AND L.IDCANCCONTRATOTS IS NULL
                AND L.IDTIPOLANCAMENTO = 7
                AND AJ.IDMOTIVO <> 3
       GROUP BY VXC.IDVENDAXCONTRATO) VALORJUROSVENDANORMAL,
        (SELECT
                VXC.IDVENDAXCONTRATO,
                VXC.TRGDTINCLUSAO,
                SUM(L.VLRLANCAMENTO) AS VALORCONTRATOTRGDTINCLUSAO
            FROM
                VENDAXCONTRATOTS VXC,
                LANCAMENTOTS L    
            WHERE
                VXC.IDVENDATS = L.IDVENDATS 
                AND TRUNC(VXC.TRGDTINCLUSAO) = TRUNC(L.TRGDTINCLUSAO)
                AND L.VLRLANCAMENTO > 0
                AND L.IDTIPOLANCAMENTO IN (1, 7)
                GROUP BY VXC.IDVENDAXCONTRATO, VXC.TRGDTINCLUSAO) VALORVENDATRGDTINCLUSAO
WHERE
        O.IDDEPARTAMENTO = D.IDDEPARTAMENTO
        AND O.IDCLIENTE = P.IDPESSOA (+) -- LEFT JOIN
        AND O.IDMOTIVOTS = M.IDMOTIVOTS
        AND O.IDUSUARIO = U.IDUSUARIO
        AND O.IDVENDAXCONTRATO = VC.IDVENDAXCONTRATO (+) -- LEFT JOIN
        AND VC.IDCONTRATOTS = C.IDCONTRATOTS (+) -- LEFT JOIN
        AND VC.IDPROJETOTS = PR.IDPROJETOTS (+) -- LEFT JOIN
        AND O.USUARIORESP = UR.IDUSUARIO (+) -- LEFT JOIN
        AND O.IDMOTIVOFINALIZA  = MF.IDMOTIVOTS (+) -- LEFT JOIN
        AND O.IDVENDAXCONTRATO = CONTRATOSREVERTIDOS.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = CONTRATOSCANCELADOS.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORVENDANORMAL.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORJUROSVENDANORMAL.IDVENDAXCONTRATO (+)
        AND O.IDVENDAXCONTRATO = VALORVENDATRGDTINCLUSAO.IDVENDAXCONTRATO (+)        
        AND D.IDDEPARTAMENTO IN (3, 83) -- ADM TS - RENEGOCIAÇÃO
        AND TO_DATE(TO_CHAR(O.DTOCORRENCIA,'dd/mm/yyyy'), 'dd/mm/yyyy') >= TO_DATE('01/06/2020', 'dd/mm/yyyy')
    ORDER BY O.IDOCORRENCIA DESC