/* - App: renegociacao
 * - Dados de contrato, data de venda validade.
 * - Derivado da query cm_resumo_financeiro
 */
SELECT C.NOME AS NOMECONTRATO,
       C.VALIDADE, 
       C.TIPOVALIDADE,
       CASE WHEN C.TIPOVALIDADE = 'A' THEN
         ADD_MONTHS(NVL(RCN.DATAREVERSAO, V.DATAVENDA), C.VALIDADE * 12)
       WHEN
         C.TIPOVALIDADE = 'M' THEN
         ADD_MONTHS(NVL(RCN.DATAREVERSAO, V.DATAVENDA), C.VALIDADE)
       ELSE
         NVL(RCN.DATAREVERSAO, V.DATAVENDA) + C.VALIDADE
       END AS DATAVALIDADE,
       C.NUMEROPONTOS,
       P.NOME AS NOMECLIENTE,
       TO_CHAR(NVL(RCN.DATAREVERSAO, V.DATAVENDA), 'YYYY-MM-DD')AS DATAVENDA,
       DECODE(RCN.DATAREVERSAO, NULL, 0, 1) AS TIPODATA,
       VC.FLGCANCELADO,
       VC.FLGREVERTIDO,
       CC.DATACANCELAMENTO,
       VC.NUMEROCONTRATO,
       RCA.DATAREVERSAO,
       V.IDVENDATS,
       CC.IDCANCCONTRATOTS,
       RCN.IDREVCONTRATOTS,
       RCA.IDREVCONTRATOTS AS IDREVCONTRATOTSANTERIOR,
       VC.DATAINTEGRALIZA,
       VC.IDVENDAXCONTRATO,
       VC.IDSEMANAFIXAUH,
       H.NOME AS HOTEL,
       S.CODUH,
       S.SEMANA,
       C.PERCPAGOALERTA,
       C.PERCPONTUACAOALERTA,
       C.OPERADORALERTA,
       NVL(VC.EXIBIRALERTAREVENDA, 'S') AS EXIBIRALERTAREVENDA
  FROM CONTRATOTS C, VENDAXCONTRATOTS VC, VENDATS V, ATENDCLIENTETS A, REVCONTRATOTS RCN, REVCONTRATOTS RCA,
       CANCCONTRATOTS CC, PESSOA P, SEMANAFIXAXUHTS S, PESSOA H
WHERE VC.IDVENDAXCONTRATO = PARAM_IDVENDAXCONTRATO  
  AND C.IDCONTRATOTS      = VC.IDCONTRATOTS
  AND V.IDVENDATS         = VC.IDVENDATS
  AND A.IDATENDCLIENTETS  = V.IDATENDCLIENTETS
  AND P.IDPESSOA          = A.IDCLIENTE
  AND VC.IDVENDAXCONTRATO = CC.IDVENDAXCONTRATO   (+)
  AND VC.IDVENDAXCONTRATO = RCN.IDVENDAXCONTRNOVO (+)
  AND VC.IDVENDAXCONTRATO = RCA.IDVENDAXCONTRANT  (+)
  AND VC.IDSEMANAFIXAUH   = S.IDSEMANAFIXAUH (+)
  AND S.IDHOTEL           = H.IDPESSOA (+)