###

http://localhost/project-default/rest/rest-import-motivos.php


###

http://localhost/project-default/rest/rest-import-projetos.php


###

http://localhost/project-default/rest/rest-import-ocorrencias.php

###

http://localhost/wser_cm/?class=MotivoServices&method=getData